some update to the pre push

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,5 +1,31 @@
 #!/bin/bash
 
+LAST_COMMIT_MESSAGE=$(git log -1 --pretty=%B)
+
+if [[ "$LAST_COMMIT_MESSAGE" != *"Auto update version"* ]]; then
+  echo "Automated commit message not found. Updating..."
+    newVersion=$(deno task version)
+    if [ $? -ne 0 ]; then
+        echo "Version update failed. Please check the issue and try again."
+        exit 1
+    fi
+
+    git add ./deno.json ./routes/index.tsx
+    if [ $? -ne 0 ]; then
+        echo "Failed to stage updated files. Please check the issue and try again."
+        exit 1
+    fi
+
+    git commit -m "Auto update version to ${newVersion}"
+    if [ $? -ne 0 ]; then
+        echo "Failed to create a commit. Please check the issue and try again."
+        exit 1
+    fi
+    
+    echo "Updated to ${newVersion}. Push again."
+    exit 1
+fi
+
 deno lint
 
 if [ $? -ne 0 ]; then
@@ -14,23 +40,4 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
-newVersion=$(deno task version)
-if [ $? -ne 0 ]; then
-    echo "Version update failed. Please check the issue and try again."
-    exit 1
-fi
-
-git add ./deno.json ./routes/index.tsx
-if [ $? -ne 0 ]; then
-    echo "Failed to stage updated files. Please check the issue and try again."
-    exit 1
-fi
-
-git commit -m "Update version to ${newVersion}"
-if [ $? -ne 0 ]; then
-    echo "Failed to create a commit. Please check the issue and try again."
-    exit 1
-fi
-
-echo "Version updated and committed successfully: ${newVersion}"
 exit 0
