add a lint to precommit

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,6 +1,13 @@
 #!/bin/bash
 
-deno fmt
+deno fmt 
+
+if [ $? -ne 0 ]; then
+    echo "Formatting failed. Please fix the issues and try again."
+    exit 1
+fi
+
+deno lint 
 
 if [ $? -ne 0 ]; then
     echo "Formatting failed. Please fix the issues and try again."
